### ISSUE TITLE
当封面的图片比例和视频比例不一致的时候，播放视频就会变形

### ISSUE THREAD

**Issue by lan2000** [zengxiangxi/photo_preview_flutter#6]
视频播放页面，封面图片的宽高比例会影响视频播放的比例。
当封面的图片比例和视频比例不一致的时候，播放视频就会变形。

```
photo_preview:
    git:
      url: https://github.com/zengxiangxi/photo_preview_flutter
      ref: flutter-2.x-nullsafe
```
